[package]
name = "adv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bytes = "1.8.0"
clap = { version = "4.5.21", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.9", features = ["blocking"] }
